# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Update FAA TFRs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install activesupport nokogiri slop
    - name: Retrieve TFRs and save output as JSON
      run: ruby scripts/faa/faa_get_tfrs json/faa/tfrs.json
    - name: Retrieve TFRs and save output as GeoJSON
      run: ruby scripts/faa/faa_get_tfrs --format=geojson json/faa/tfrs.geojson
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Kevin Elliott
        author_email: kevin@welikeinc.com
        message: "Update FAA TFRs - json/faa/tfrs.json and json/faa/tfrs.geojson"
        add: "*.*json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
